.PHONY:  all menu vorspeise salat-putzen dressing-herstellen kraeuter-hacken hauptgericht kartoffeln-kochen kartoffeln-schneiden wasser-aufsetzen fleisch-zubereiten fleisch-anbraten fleisch-schneiden fleisch-wuerzen dessert mit-schoko-garnieren gruetze-verteilen eis-portionieren

all: menu

menu: dessert hauptgericht vorspeise
	@echo Alles geschafft!

vorspeise: salat-putzen dressing-herstellen
	@echo Vorspeise servieren...

salat-putzen: 
	@echo Salat putzen.

dressing-herstellen: kraeuter-hacken
	@echo Dressing herstellen.

kraeuter-hacken: 
	@echo Kräuter hacken.

hauptgericht: fleisch-zubereiten kartoffeln-kochen vorspeise
	@echo Hauptgericht servieren...

kartoffeln-kochen: wasser-aufsetzen kartoffeln-schneiden
	@echo Kartoffeln kochen.

kartoffeln-schneiden: 
	@echo Kartoffeln schneiden.

wasser-aufsetzen: 
	@echo Wasser aufsetzen.

fleisch-zubereiten: fleisch-anbraten fleisch-wuerzen
	@echo Fleisch zubereiten.

fleisch-anbraten: fleisch-schneiden
	@echo Fleisch anbraten.

fleisch-schneiden: 
	@echo Fleisch schneiden.

fleisch-wuerzen: 
	@echo Fleisch würzen.

dessert: hauptgericht mit-schoko-garnieren
	@echo Dessert servieren...

mit-schoko-garnieren: gruetze-verteilen
	@echo Mit Schokoladenraspeln garnieren.

gruetze-verteilen: eis-portionieren
	@echo Grütze verteilen.

eis-portionieren: 
	@echo Eis portionieren.

